--DROP TABLE student CASCADE CONSTRAINT;
--DROP TABLE university CASCADE CONSTRAINT;

CREATE TABLE university (
	OIB INT NOT NULL CONSTRAINT university_OIB_pk PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	address VARCHAR(50) NOT NULL
);

CREATE TABLE student (
	OIB INT NOT NULL CONSTRAINT student_OIB_pk PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	universityOIB INTEGER NOT NULL CONSTRAINT student_fk_universityOIB REFERENCES university(OIB) 
);
